# IMAGEN BASE
FROM node:22-alpine3.19

#INSTALAMOS PNPM
RUN npm install -g pnpm

#CARPETA DE LA APLICACION DENTRO DEL CONTENEDOR
WORKDIR /app

#COPIAMOS EL CODIGO DE LA APLICACION DENTRO DE LA CARPETA DEL CONTENEDOR
COPY . .

#INSTALAMOS EL PACKAGE
RUN pnpm install && pnpm run build

#LEVANTAMOS LA APLICACION
CMD ["pnpm", "run", "start"]